version: 2
builds:
  - id: muffy
    binary: muffy
    builder: rust
    flags: --release
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
