name: Muffy
description: The static website validator
branding:
  icon: link
  color: yellow
inputs:
  url:
    description: A website URL
    required: true
outputs: {}
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
