[package]
name = "muffin"
description = "The static website validator"
repository = "https://github.com/raviqqe/muffin"
keywords = ["web"]
categories = ["command-line-utilities", "development-tools"]
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
html5ever = "0.31.0"
markup5ever_rcdom = "0.3.0"
reqwest = "0.12.15"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }

[lints.rust]
missing_docs = "deny"
warnings = "deny"

[lints.clippy]
cargo = "deny"
complexity = "deny"
correctness = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"

alloc_instead_of_core = "deny"
dbg_macro = "deny"
derive_partial_eq_without_eq = "deny"
equatable_if_let = "deny"
explicit_deref_methods = "deny"
if_not_else = "deny"
manual_let_else = "deny"
missing_const_for_fn = "deny"
missing_panics_doc = "deny"
multiple_crate_versions = { level = "allow", priority = 1 }
option_if_let_else = "deny"
std_instead_of_alloc = "deny"
std_instead_of_core = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
unimplemented = "deny"
uninlined_format_args = "deny"
unnecessary_safety_comment = "deny"
unused_self = "deny"
use_self = "deny"
