[package]
name = "muffin"
description = "The static website validator"
repository = "https://github.com/raviqqe/muffin"
keywords = ["web"]
categories = ["command-line-utilities", "development-tools"]
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
bincode = "2.0.1"
clap = { version = "4.5.37", features = ["derive"] }
colored = "3.0.0"
dashmap = "6.1.0"
futures = "0.3.31"
html5ever = "0.27.0"
http = "1.3.1"
markup5ever = "0.16.1"
markup5ever_rcdom = "0.3.0"
reqwest = "0.12.15"
rlimit = "0.10.2"
scc = "2.3.4"
sled = "0.34.7"
tabled = "0.19.0"
tokio = { version = "1.44.2", features = [
  "io-std",
  "io-util",
  "macros",
  "rt-multi-thread",
  "sync",
] }
url = "2.5.4"

[lints.rust]
missing_docs = "deny"
warnings = "deny"

[lints.clippy]
cargo = "deny"
complexity = "deny"
correctness = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"

alloc_instead_of_core = "deny"
dbg_macro = "deny"
derive_partial_eq_without_eq = "deny"
equatable_if_let = "deny"
explicit_deref_methods = "deny"
if_not_else = "deny"
manual_let_else = "deny"
missing_const_for_fn = "deny"
missing_panics_doc = "deny"
multiple_crate_versions = { level = "allow", priority = 1 }
option_if_let_else = "deny"
std_instead_of_alloc = "deny"
std_instead_of_core = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
unimplemented = "deny"
uninlined_format_args = "deny"
unnecessary_safety_comment = "deny"
unused_self = "deny"
use_self = "deny"
