[package]
name = "muffin"
description = "The static website validator"
version = "0.1.0"
edition = "2024"

[dependencies]
html5ever = "0.31.0"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
