name: release
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  rust_release:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'release' || 'test' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: raviqqe/cargo-cache@v1
      - run: cargo install cargo-workspaces
      - run: cargo workspaces publish -y --from-git
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        if: github.ref == 'refs/heads/main'
  docker_release:
    needs: rust_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ vars.DOCKER_USER }} --password-stdin
        if: ${{ github.ref == 'refs/heads/main' }}
      - id: version
        run: |
          echo version=$(git tag --points-at | sed s/^v//) >> ${{ github.outputs }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: raviqqe/muffy:latest${{ steps.version.outputs.version && join(',raviqqe/muffy:', steps.version.outputs.version) || '' }}
  release:
    needs:
      - rust_release
      - docker_release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
